# Generated by Django 4.2.6 on 2024-08-23 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Deck",
            fields=[
                ("deck_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("last_seen_card_id", models.IntegerField(blank=True, null=True)),
                ("number_of_cards", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FlashCard",
            fields=[
                ("card_id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                (
                    "confidence",
                    models.IntegerField(
                        choices=[(0, "None"), (1, "Low"), (2, "Medium"), (3, "High")],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flashcards.deck",
                    ),
                ),
            ],
        ),
    ]
