# Generated by Django 4.1.5 on 2024-03-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="confidence",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Low"), (2, "Medium"), (3, "High")], default=0
            ),
        ),
    ]
