services:
  backend:
    volumes:
      - static:/app/static
      - validation:/app/validation
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/app/dist

  nginx:
    build:
      context: ./nginx
    volumes:
      - static:/app/static
      - frontend:/var/www/frontend
      - validation:/app/validation
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

 

volumes:
  static:
  frontend:
  validation: